// Find unsigned/rare new process from user profile folder
//
// Use a dynamic baseline and fileprofile
//
let DetectionWindow = 1d;
let LookbackWindow = 30d;
let ExcludedProcess = dynamic([
    "bin.exe"
]);
let KnownSigners = dynamic([
    "Microsoft Corporation"    
]);
let HistoricProcesses = 
DeviceProcessEvents
    | where TimeGenerated between (ago(LookbackWindow) .. ago(DetectionWindow))
    | where FolderPath startswith @"C:\Users"
    | extend Artifacts = strcat(DeviceName, ":", SHA1)
    | distinct Artifacts;
//HistoricProcesses
DeviceProcessEvents
| where TimeGenerated > ago(DetectionWindow)
| where FolderPath startswith @"C:\Users"
| extend Artifacts = strcat(DeviceName, ":", SHA1)
| where Artifacts !in (HistoricProcesses)
| invoke FileProfile(SHA1)
| where Signer !in (KnownSigners) or IsCertificateValid != "1"
| project TimeGenerated, AccountUpn, DeviceName, FolderPath, FileName, GlobalFirstSeen, GlobalPrevalence, Signer, ProcessVersionInfoCompanyName, ProcessVersionInfoFileDescription, ProcessVersionInfoProductName
